version: '3.8'
networks:
  app_network:
services:
  battleship-service-1:
    container_name: battleship-service-1
    build:
      context: ./
    image: battleship-service-1
    ports:
      - "8081:9000"
    environment:
      - DB_POSTGRES_CONNECTION=jdbc:postgresql://localhost:5432/postgres?user=postgres&password=postgrespassword
      - DB_POSTGRES_BATTLESHIPS_TESTS_CONNECTION=jdbc:postgresql://localhost:5432/BattleshipsTests?user=postgres&password=postgrespassword
    depends_on:
      - db
      - dbtest
    networks:
      - app_network
  battleship-service-2:
    container_name: battleship-service-2
    build:
      context: ./
    image: battleship-service-2
    ports:
      - "8082:9000"
    environment:
      - DB_POSTGRES_CONNECTION=jdbc:postgresql://localhost:5432/postgres?user=postgres&password=postgrespassword
      - DB_POSTGRES_BATTLESHIPS_TESTS_CONNECTION=jdbc:postgresql://localhost:5432/BattleshipsTests?user=postgres&password=postgrespassword
    depends_on:
      - db
      - dbtest
    networks:
      - app_network
  db:
    container_name: db
    image: postgres:14.1-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgrespassword
      - POSTGRES_DB=postgres
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - db-data:/var/lib/postgresql/data1
      - ./src/main/sql/create.sql:/docker-entrypoint-initdb.d/create.sql
      - ./src/main/sql/triggers.sql:/docker-entrypoint-initdb.d/triggers.sql
  dbtest:
    container_name: dbtest
    image: postgres:14.1-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgrespassword
      - POSTGRES_DB=BattleshipsTests
    ports:
      - "5433:5433"
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - db-data:/var/lib/postgresql/data2
      - ./src/main/sql/create.sql:/docker-entrypoint-initdb.d/create.sql
      - ./src/main/sql/triggers.sql:/docker-entrypoint-initdb.d/triggers.sql
  nginx:
    container_name: nginx
    image: nginx
    ports:
      - "9000:9000"
    volumes:
      - ./:/etc/nginx
    depends_on:
      - battleship-service-1
      - battleship-service-2
    networks:
      - app_network
volumes:
  db-data:
    driver: local
