version: '3.8'
services:
  app:
    image: app
    container_name: app
    build:
      context: ../../js
    ports:
      - "8080:8080"
    environment:
        - API_PROXY_TARGET='http://host.docker.internal:9000/'
  battleship-service-1:
    container_name: battleship-service-1
    build:
      context: ./
    image: battleship-service-1
    ports:
      - "8081:9000"
    environment:
      - DB_POSTGRES_CONNECTION=jdbc:postgresql://db:5432/battleship?user=postgres&password=password
      - DB_POSTGRES_BATTLESHIPS_TESTS_CONNECTION=jdbc:postgresql://dbtest:5432/battle_shiptest?user=postgres&password=password
    depends_on:
      db:
        condition: service_healthy
      dbtest:
        condition: service_healthy
    links:
      - db
      - dbtest
  battleship-service-2:
    container_name: battleship-service-2
    build:
      context: ./
    image: battleship-service-2
    ports:
      - "8082:9000"
    environment:
      - DB_POSTGRES_CONNECTION=jdbc:postgresql://db:5432/battleship?user=postgres&password=password
      - DB_POSTGRES_BATTLESHIPS_TESTS_CONNECTION=jdbc:postgresql://dbtest:5432/battle_shiptest?user=postgres&password=password
    depends_on:
      db:
        condition: service_healthy
      dbtest:
        condition: service_healthy
    links:
      - db
      - dbtest
  db:
    container_name: db
    hostname: db
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=battleship
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./src/main/sql/create.sql:/docker-entrypoint-initdb.d/create.sql
      - ./src/main/sql/triggers.sql:/docker-entrypoint-initdb.d/triggers.sql
  dbtest:
    container_name: dbtest
    hostname: dbtest
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=battle_shiptest
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - db-data-test:/var/lib/postgresql/data
      - ./src/main/sql/create.sql:/docker-entrypoint-initdb.d/create.sql
      - ./src/main/sql/triggers.sql:/docker-entrypoint-initdb.d/triggers.sql
  nginx:
    container_name: nginx
    image: nginx
    ports:
      - "9000:9000"
    volumes:
      - ./:/etc/nginx
    depends_on:
      - battleship-service-1
      - battleship-service-2
      - app
volumes:
  db-data:
    driver: local
  db-data-test:
    driver: local

